# 這個檔案用來存 design 頁面的設定，對一般使用者沒有影響

menu:
  - title: og
    url: /design/og/
  - title: redirect
    url: /design/redirect/
  - title: actions
    url: /design/actions/
  - title: content
    url: /design/content/
  - title: layout
    url: /design/layout/
  - title: data
    url: /design/data/
  - title: ui
    url: /design/ui/
