# 這個檔案用來存 people 頁面的設定，影響範圍包括
# 1.people 頁的內容有哪幾塊、每塊的小標題是什麼
# 2.people 頁上方的 menu 會出現哪些按鈕

card:
# 位於頁面的第一區，用 semantic ui 的 card 的方式呈現。在這裡調整順序，網頁上的順序也會跟著變。
# id: 要從 individuals 內的哪個 .yml 檔案讀取這群人的名單
# name: 網頁上的小標題要顯示什麼字
  - id: staff
    name: 工作人員
  - id: consultants
    name: 顧問
#  - id: intern
#    name: 實習夥伴
  - id: volunteers
    name: 熱血志工
  - id: board
    name: 董事

logo:
# 位於頁面的第二區，用 logo 牆的方式呈現。在這裡調整順序，網頁上的順序也會跟著變。
# id: 要從 orgs 內的哪個 .yml 檔案讀取這群組織的名單
# name: 網頁上的小標題要顯示什麼字
  - id: partners
    name: 合作夥伴
  - id: sponsors
    name: 贊助夥伴

# label:
# 位於頁面的第三區，用 semantic ui 的 label 的方式呈現。
# id: 要從 individuals 內的哪個 .yml 檔案讀取這群組織的名單
# name: 網頁上的小標題要顯示什麼字
  #- id: donors
    #name: 捐助人


# 以下設定顯示在 2020 版專案頁 / 活動頁 meta 區塊的文字

orgs:
  advisor:
    name: 指導
    name_en: Advisor
  organizer:
    name: 主辦
    name_en: Organizer
  co-organizer:
    name: 協辦
    name_en: Co-organizer
  implementer:
    name: 承辦
    name_en: Case Handling Unit
  sponsor:
    name: 贊助
    name_en: Sponsor

individuals:
  coordinator:
    name: 召集人
    name_en: Coordinator
  case-handler:
    name: 接洽窗口
    name_en: Case handler
  co-worker:
    name: 協力
    name_en: Co-worker
  board:
    name: 董事
    name_en: Board
  staff: 
    name: 工作人員
    name_en: Staff
  consultant:
    name: 顧問
    name_en: Consultant
  intern:
    name: 實習夥伴
    name_en: interns
  volunteer:
    name: 志工
    name_en: Volunteer
  contributor:
    name: 貢獻者
    name_en: Contributor
  host:
    name: 主持
    name_en: Host
  speaker:
    name: 主講
    name_en: Speaker
  participant:
    name: 參與
    name_en: Participant
  donor:
    name: 捐助人
    name_en: Donor
